openapi: 3.0.0
info:
  title: Jobs API by ThomasAlan
  version: 1.0.0
servers:
  - url: https://temp-jobs-api-9ki3.onrender.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /api/v1/auth/register:
    post:
      tags:
        - Auth
      summary: Register User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: antetokounpo
                email: ante34g@gmail.com
                password: secret
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/login:
    post:
      tags:
        - Auth
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: anna@gmail.com
                password: secret
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/jobs:
    post:
      tags:
        - Jobs
      summary: Create Job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: netfix
                position: back-end developer
      security:
        - bearerAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzA2ZjlmZDJjYjQ1YTI1OThkYjVmZDEiLCJuYW1lIjoiYW5uYSIsImlhdCI6MTcyODUxMDQ2MSwiZXhwIjoxNzMxMTAyNDYxfQ.jlxqzN7hL0JOQ--x3KF72g8D33u2xln4l2lpVwxYupI
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Jobs
      summary: GET All Jobs
      security:
        - bearerAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzA2ZjlmZDJjYjQ1YTI1OThkYjVmZDEiLCJuYW1lIjoiYW5uYSIsImlhdCI6MTcyODUxMDQ2MSwiZXhwIjoxNzMxMTAyNDYxfQ.jlxqzN7hL0JOQ--x3KF72g8D33u2xln4l2lpVwxYupI
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The job ID
    get:
      tags:
        - Jobs
      summary: GET Single Job
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  
    patch:
      tags:
        - Jobs
      summary: UPDATE Job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: random company
                position: Full-stack developer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Jobs
      summary: DELETE Job
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
